services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitorit-app
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://nexolab:PasswordKuat123!@36.95.224.205:5432/monitoring_it
      - NODE_ENV=production
